### ISSUE TITLE
Provisioning not working

### ISSUE THREAD

**Issue by Lawrence-Godfrey** [xinabox/XinaBoxUploader#2]
### On v1.0.8 and v1.0.9: 
Using the provisioning WiFi example on the CW01. No window comes up for the SSID or Password. Provisioning Works on v1.0.7.

**Comment by gotfredsen** [comment]
Should be fixed in v1.1.0, please verify.

**Comment by oitar1** [comment]
Issue still occurring in version 1.1.0c.
Seems to be related to USB port. Downloaded from same source(github) on a laptop and desktop. When running on the laptop keeps showing a beta letter after version number, and fails to launch provisioning window almost all the time. On desktop pc( no beta letter after version ), seems to work fine on USB2.0 ports, fails most of the time on USB3.0.
